framework:
  messenger:
    serializer:
      default_serializer: messenger.transport.native_php_serializer
      symfony_serializer:
        format: json
        context: { }

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async-product-replica:
        dsn: "%env(string:MESSENGER_TRANSPORT_DSN)%/product-replica"
        serializer: messenger.transport.native_php_serializer
        options:
          auto_setup: true
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 0

    routing:
      'CommonBundle\ValueObject\ProductValue': async-product-replica
